### ISSUE TITLE
Error: static assert  (8LU == 4LU) is false

### ISSUE THREAD

**Issue by yannick** [DigitalMars/DMDScript#7]
i'm trying to build the ds project with dub but i get:

```
.dub/packages/dmdscript-master/engine/source/dmdscript/expression.d(318,9): Error: static assert  (8LU == 4LU) is false
```

**Comment by UplinkCoder** [comment]
seems like an 32 vs. 64bit issue

**Comment by s-ludwig** [comment]
The question is what to do here: https://github.com/DigitalMars/DMDScript/blob/master/engine/source/dmdscript/irstate.d#L153

The 64-bit value could be split into two `uint` slots, the slots could be changed to `ulong`, or the 64-bit value could be "hashed" down to a 32-bit value. I didn't trace deep enough through the source code to discover the actual implications, but converting `data` to `uintptr_t[]` sounds like the only safe approach.
